### ISSUE TITLE
Black Screen after update???

### ISSUE THREAD

**Issue by timbuktu031** [bugsounet/MMM-GoogleAssistant#100]
There is an update notification on the screen.
I update by 'git pull' 
It doesn't work after that.
Black screen!!! 

Is the update method wrong? 
What should I do?

**Comment by bugsounet** [comment]
Can you read [Wiki](https://github.com/bugsounet/MMM-GoogleAssistant/wiki#misc) pages please ?

you will see `updating`

**Comment by timbuktu031** [comment]
sorry^^
