### ISSUE TITLE
GA is not working

### ISSUE THREAD

**Issue by nguyenanhminh97** [bugsounet/MMM-GoogleAssistant#101]
when I call jarvis, my GA is activated and receives my command (for example: what time is it), and then GA does not work, does not exit the command prompt, the GA mic icon is running continuously continuous and non-stop.
I can only fix it with ctrl + q and restart GA
I want to ask if there is any way to fix the error or the modules / features that help me reload MM automatically in the above case (replace ctrl + q and restart MM)
thanks

**Comment by lxne** [comment]
If it is a GUI crash you could try https://github.com/MichMich/MMM-WatchDog

For more help, more information would be needed.
Hardware, MagicMirror version, other modules used ...

**Comment by bugsounet** [comment]
> the GA mic icon is running continuously continuous and non-stop

Euh... There no mic icon in this module. It's Only on GA v1
In latest version there is not this. 
Please update the module with a clean install. And read wiki
