### ISSUE TITLE
GA doesn't remind or set alarms.

### ISSUE THREAD

**Issue by kkongchi-maker** [bugsounet/MMM-GoogleAssistant#102]
everything is working fine and well. however, when I ask GA "please reminder in 5 mins to drink water", it says "reminder is set" but when 5 minutes passes, nothing happens. why is this?

**Comment by bugsounet** [comment]
Hi,
This feature is not yet supported natively by [Google Assistant SDK API](https://developers.google.com/assistant/sdk/overview)
