### ISSUE TITLE
Ok google hotword

### ISSUE THREAD

**Issue by min-vison** [bugsounet/MMM-GoogleAssistant#115]
Hello,

Firstly thank for this module it work like charms :)

It's possibly to add 'ok google' hotword to triggle the google assistant ? 

Thnak you

**Comment by bugsounet** [comment]
Hi,

Thanks for your feedback,

can you read this [issue](https://github.com/bugsounet/MMM-GoogleAssistant/issues/110) ?

Thanks ;)
