### ISSUE TITLE
Blank screen after installation

### ISSUE THREAD

**Issue by Jouhney** [bugsounet/MMM-GoogleAssistant#116]
Hey everybody
I installed the module because I want a Google Assistant on my Mirror. But however, the screen is now just black after the installation. I think I did everything right. Does someone have an idea of what the issue is?

Edit: I checked the log and I've got an error message that says: "MODULE_NOT_FOUND". After that, it says: requireStack and it shows me directories in MagicMirror/modules/MMM-GoogleAssistant. I checked them and in the last directory, it shows me there's something odd. In /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js there is no folder called default_app.asar, just a file. So there can't be the file main.js... right?

Thank you very much

**Comment by bugsounet** [comment]
Hi,

if you have a "MODULE_NOT_FOUND" message, it's meems that all needed module was not installed correctly
maybe electron rebuild step ?
or maybe you have do `npm fix` command

in all case retry with `npm run rebuild` in GA directory and don't do another `npm` commands after installation done
If there is some error (red line)  when installing : paste the error part there (ALL red line)

**Comment by Jouhney** [comment]
The last command helped. Thank you so much!

**Comment by bugsounet** [comment]
perfect so ;)
