### ISSUE TITLE
Make onscreen buttons and links clickable?

### ISSUE THREAD

**Issue by Electro40** [bugsounet/MMM-GoogleAssistant#119]
In other words, when I try to click on any of the Spotify controls or links within the MM display, they don't respond when Google Assistant is enabled.

**Comment by bugsounet** [comment]
I have not set any callbacks for this :)

Just use [MMM-Assistant2Display](https://github.com/bugsounet/MMM-Assistant2Display) extension and it will be open automaticaly ;)
