### ISSUE TITLE
hotword detector (*.pmdl)

### ISSUE THREAD

**Issue by MrDondoT** [bugsounet/MMM-GoogleAssistant#128]
I've tried to use a personal model  (rachele.pmdl) as snowboy wake word in the config.js file

				`},
				snowboy: {
				  audioGain: 2.0,
				  Frontend: true, //use true with other models
				  Model: "rachele", 
				  Sensitivity: 0.7 //null
				},`

and put the file in the same dir of the other models:
/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/resources/models
but the mm will continue restarting with errors:

![image](https://user-images.githubusercontent.com/46877452/90669408-e7f45800-e251-11ea-941c-86a76d11815c.png)

please advise
I also would suggest to write a note about it in the documentation.

**Comment by bugsounet** [comment]
like i said on the forum i plan to do it ;)
Actually it's not coded in my npm library `@bugsounet/snowboy`  core

I will add it soon :)

**Comment by bugsounet** [comment]
now coded with v2.4.2 (with @bugsounet/snowboy v1.6.0 npm library)

to update:
`npm run update` in the GA directory

and read wiki (snowboy part and structure)

**Comment by bugsounet** [comment]
Note: I add a Global notice for @ktoanlba89 on start of @bugsounet/snowboy and GA/A2D : **copying my MagicMirror modules don't pay !**
I think, i will understand why...

**Comment by MrDondoT** [comment]
@bugsounet I'll update later on tonight and test it.
thanks
