### ISSUE TITLE
Réduire frame youtube ?

### ISSUE THREAD

**Issue by declic29** [bugsounet/MMM-GoogleAssistant#140]
Bonjour,
Les modules fonctionnent nickel toutefois est il possible d'ajouter un paramètre dans le config.js pour réduire la fenêtre d'affichage de youtube ? Ou même la supprimer tout en gardant le son des videos ?
Merci

**Comment by bugsounet** [comment]
c'est possible mais trop compliqué a gérer avec le structure actuelle de GA
par exemple tous les modules sont desactivé pour afin de donner le maximum de puissance au RPI

Il faudrait revoir TOTALEMENT la gestion... et c'est un enfer ! apres reoptimiser le tout ...

Note:
* la lecture d'une video en plein ecran c'est deja compliqué a afficher... et sutout que ce soit fluide !
* donc imaginez minimisé (processus non prioritaire...), risque de lag, coupure de son, son de la video qui ne se lance pas,...

donc non, je ne le coderai pas désolé ;)
