### ISSUE TITLE
I Have question about custom action..

### ISSUE THREAD

**Issue by angel20123** [bugsounet/MMM-GoogleAssistant#153]
First, I read Wiki already.. that is action category. 

When I use command line(below).. have some problems.

 > ./gactions test --action_package ../tmp/action_package.json --project *YOUR_PROJECT_ID*

1. have error log. ( log content : "gactions login" command use)
2. when I use 'gactions login', I can see web browser for google login page. but after logining, I have some problem.
3.  2 problme is same this link.. (https://github.com/googlesamples/assistant-sdk-python/issues/376)

Do you have any Idea ..?

**Comment by bugsounet** [comment]
hi,

wiki says [there](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/actions)

>At this moment, Google haven't updated linux-arm gaction, so it might not work. Others are fine.
