### ISSUE TITLE
How to change popup location?

### ISSUE THREAD

**Issue by ashwinjohri** [bugsounet/MMM-GoogleAssistant#154]
Hi, I'm trying to make the notification appear from the bottom of the screen. Can this be done by editing the screen_output.css file?  If so, is there an easy change. I'm a total noob so any and all help would be greatly appreciated!

**Comment by bugsounet** [comment]
> If so, is there an easy change. I'm a total noob

screen_output.css is the google response css file,
you can't change position with it and not the position

use custom.css and `#GA_HELPER` css tag
you can see it in MMM-GoogleAssistant.css

Notes: 
* i use an iframe for displaying the response content
* ANY change on original files will be reseted on update
* use `npm start dev` for open console tools
* so use `css/custom.css` in `MagicMirror` folder for override default value (or for past result final result from the dev console)
* If you are noob... it's very difficult to do...
