### ISSUE TITLE
Update notification for GoogleAssistant

### ISSUE THREAD

**Issue by tdungsi1** [bugsounet/MMM-GoogleAssistant#155]
Hello,
I updated GoogleAssistant to the newest version. I installed MMM-Assistant2Display and the npm check kept saying that "Update available for MMM-GoogleAssistant module, [NPM] @bugsounet/npmcheck v0.9.6 -> v0.9.7

![image](https://user-images.githubusercontent.com/26120816/92705805-3347e500-f37e-11ea-85b9-45c6b5210be8.png)

**Comment by bugsounet** [comment]
Hello,

precisely, I lost the wiki page ... you can remind me please?

**Comment by tdungsi1** [comment]
Sorry, my bad.
May I ask you two more questions?
I tried to use personal hotword, I put the pmdl file into the components directory, then changed config.js model to The_Name
But It doesnt work. 

My config.js:
![image](https://user-images.githubusercontent.com/26120816/92708490-5c697500-f380-11ea-9db1-c93e587a6993.png)

Name in the directory:
![image](https://user-images.githubusercontent.com/26120816/92708595-70ad7200-f380-11ea-81ac-a8c8d2490230.png)


And my output on screen:

![image](https://user-images.githubusercontent.com/26120816/92708364-42c82d80-f380-11ea-8144-01c8495fb17b.png)


Thanks for helping.

**Comment by bugsounet** [comment]
If you found the wiki page ... EVERYTHING is explain :)

I will not lost my time to copy/past !
sorry

**Comment by bugsounet** [comment]
Wiki says : 
# Assume:
 * If you don't use this command, don't open ANY issue for updating problem... It's will be closed automaticaly without reponse !
 * If you don't want READ this part... so I don't want respond to your issue !
