### ISSUE TITLE
Don't display Youtube play...

### ISSUE THREAD

**Issue by phuctu1901** [bugsounet/MMM-GoogleAssistant#171]
Last week, I installed MM with MMM-GoogleAssistant and MMM-Asssistant2Display, everything are working well. But few days ago, I can't command MM to play and display Youtube video. Another functions are still working. Thank for your support.

**Comment by bugsounet** [comment]
Hi related to [this](https://github.com/bugsounet/MMM-Assistant2Display/issues/129)

**Comment by phuctu1901** [comment]
Thank you very much. I'm look forward to your fix and your MagicMirror version.
