### ISSUE TITLE
 I think there is something wrong with the audio

### ISSUE THREAD

**Issue by jinnij21** [bugsounet/MMM-GoogleAssistant#173]
[SNOWBOY] Retry restarting...
[LPCM16] WARN: arecord; main: 828:
[LPCM16] WARN: audio open error: No such file or directory << LOG

I am not sure about this issue.
Speaking Smart Mirror does not respond All audio settings have been checked.
Please help with this LOG.
Thanks

**Comment by smartmirrordanifranci** [comment]
f

**Comment by bugsounet** [comment]
> [LPCM16] WARN: audio open error: No such file or directory

Means GA don't find your mic in the device defined in your config
Just verify your config and/or correct your device value
