### ISSUE TITLE
Repeating itself

### ISSUE THREAD

**Issue by Surixx** [bugsounet/MMM-GoogleAssistant#177]
When i try to speak to the Assistant it is answering me but the same time i hear 2 times or more. And another issue is that speker problem sometimes its cracks and this time the restart help.

**Comment by bugsounet** [comment]
I think you have launched GA 2 times ... (generally MMM-RemoteControl do it itself)

**Comment by Surixx** [comment]
And how can i fix this because i couldnt find any solution???

**Comment by bugsounet** [comment]
in this case, you have 2 solutions

1) Don't use RemoteControl or eq
2) don't use module who can't be duplicate, sample:
  - Pir sensor module
  - Telegram module
  - Google Assistant Module
  - *** Google Modules (APIs)
  - Alexa module
  - Spotify module
  - Deezer module
  - *** Amazon modules
