### ISSUE TITLE
Authentification problem (Oaut)

### ISSUE THREAD

**Issue by geoek** [bugsounet/MMM-GoogleAssistant#179]
Hi !
I have a problem during the authentification of application. I followed the tutorial instructions but here is the resultat on my miror : 

![IMG_20201015_110650](https://user-images.githubusercontent.com/10274046/96103088-8c53ed00-0ed7-11eb-81e3-30c4f14e892c.jpg)

I try several settings on the OAut authorisation screen of google console, but it doesn't work (i think it is a bit different from when the tutorial was written.

Do you have an idea ? Thanks in advance

**Comment by bugsounet** [comment]
yes it's possible, @sdetweil have report to me but not again correct it

**Comment by Starzs906** [comment]
Im having the same problem. Is there any sort of fix ?

**Comment by r4zi3lrrr** [comment]
I'm also getting the same!

**Comment by bugsounet** [comment]
wiki upgraded, try sdetweil version of GA setup
