### ISSUE TITLE
Can't see the google assistant bar.

### ISSUE THREAD

**Issue by jhbirdchoi** [bugsounet/MMM-GoogleAssistant#182]
Hi

I installed Magic Mirror & MMM-GoogleAssistant.
And when i run "nom run start", Magic Mirror works well.

But after I run Magic Mirror after adding MMM-GoogleAssistant, I can see the google assistant bar and it prints out that the credentials.json file could not be found.
So I added the credentials.json and token file in the MMM-GoogleAssistant.
And I run "nom run start",  google assistant bar is not visible.

When I checked the screen with the mouse, the location of the google assistant bar appears blank.

What should I check?

.raspberry 4
.raspbian 10
.node/npm version is ok
.mic & speaker works wel.

thanks

**Comment by bugsounet** [comment]
wiki says: 
There is no Google Assistant Icon. Google Assistant screen only appears on activation

google assistant bar is a popup so no position about it :)
so google assisant bar appears ONLY want you call the assistant
