### ISSUE TITLE
Prototype Pollution in node-forge  HELP

### ISSUE THREAD

**Issue by Adel51** [bugsounet/MMM-GoogleAssistant#185]
Hi,
at the end of the installation, I ve 1 high vulnerability : Prototype Pollution in node-forge.
What can i do?

MMM-GoogleAssistant is now installed !
Press [Enter] to continue

npm notice created a lockfile as package-lock.json. You should commit this file.
added 308 packages from 226 contributors and audited 308 packages in 2172.625s

8 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant $ npm audit

                       === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution in node-forge                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-forge                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.10.0                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-ga                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-ga > @bugsounet/google-assistant >         │
│               │ google-auth-library > gtoken > google-p12-pem > node-forge   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1561                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 308 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by bugsounet** [comment]
and what wiki says ?
