### ISSUE TITLE
Taille

### ISSUE THREAD

**Issue by Adel51** [bugsounet/MMM-GoogleAssistant#186]
Voici sur mon petit écran :

![20201106_180459](https://user-images.githubusercontent.com/36155818/98396676-6517b800-205e-11eb-91cb-7b47314f68cc.jpg)

et voici sur le grand écran 

![20201106_182133](https://user-images.githubusercontent.com/36155818/98397196-4239d380-205f-11eb-8a3a-1394ad3be66b.jpg)

**Comment by bugsounet** [comment]
bonjour, pour ceci je ne peux rien faire,

Je demande l'affichage de la page web en plein écran, donc c'est malheusement le site en lui meme qui demande ceci.
Donc c'est le site en lui meme qui n'est pas compatible avec votre résolution.

Essayez avec de faire un recherche sur wikipédia, je pense que cela devrai être correcte

**Comment by Adel51** [comment]
Bonjour,
j'ai fait le teste avec une recherche Wiki et ça donne ceci : 
![20201109_005945](https://user-images.githubusercontent.com/36155818/98488189-00a85480-2228-11eb-825c-84de7f5fcad0.jpg)

En fait, tout est petit sur ma TV (horloge, telegram, news, monitor, wifi, etc) : 
![20201109_005441](https://user-images.githubusercontent.com/36155818/98488215-2b92a880-2228-11eb-968d-90bec75d9925.jpg)

une idée?

Autre question : pensez vous que ce detecteur de mouvement pour arduino peut être utiliser pour le module PIR ?
voici l url du detecteur : 
https://www.bip-electronique.fr/cartes-de-developpement-et-accessoires-/4108-capteur-de-mouvement-pour-arduino.html

Merci d avance.

**Comment by Adel51** [comment]
salut
j ai trouvé. J ai modifié un paramétrage sur la resolution dans buster ey c est beaucoup plus gros

**Comment by bugsounet** [comment]
oui il suffit de zoomer
