### ISSUE TITLE
no links are visually displayed to me

### ISSUE THREAD

**Issue by comturaRalph** [bugsounet/MMM-GoogleAssistant#188]
Hello,

First of all, many thanks for the great module!

I was able to install everything without errors.

Unfortunately, no links are visually displayed to me.

the entry in the config is "true"

Could you please help me?

many thanks

**Comment by bugsounet** [comment]
Hi, there is many change in Google Server for SDK project, there is no many callback with links.

actually only weather and wikipedia works (maybe orther....)
When i have some time, i will see what can i do for Youtube, spotify and links features (maybe declared an app for open and discover the links)

**Comment by comturaRalph** [comment]
Hello,

Thank you for your response.

For me, Wikipedia and the weather don't work either.

The weather is only visualized in the small display at the bottom of the screen.

**Comment by bugsounet** [comment]
do you have set `electronOptions` ?

**Comment by comturaRalph** [comment]
I think so. I added the following code in the config:

var config = {
  address: "localhost",
  electronOptions: {
    webPreferences: {
      webviewTag: true
    }
  },
  port: 8080,

do I have to do anything else?

**Comment by comturaRalph** [comment]
it works :-)
However, I can't get Spotify to work.

I don't have a premium account, but it should still work, right?

My configuration is as follows:

    spotify: {
      useSpotify: true,
      useIntegred: true,
      useLibrespot: false,
      connectTo: "MMSpiegel",
      playDelay: 3000,
      minVolume: 10,
      maxVolume: 100,
      updateInterval: 1000,
      idleInterval: 10000,
      username: ".... @ googlemail.com",
      password: "xxxxxxxxxxx",
      CLIENT_ID: "c8 .......",
      CLIENT_SECRET: "94 ......",
      deviceDisplay: "Listening on",
      usePause: true,
      typeArtist: "artist",
      typePlaylist: "playlist",
      typeAlbum: "album",
      typeTrack: "track"
    },

I made the settings in the with-MMM-Spotify according to their instructions.

Do you have a tip why it still doesn't work?

**Comment by comturaRalph** [comment]
Thank you for your help :-)
