### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by josooik** [bugsounet/MMM-GoogleAssistant#19]
Hi!
MMM-AssistantMk2 -> Has MMM-GoogleAssistant changed?

**Comment by sudoreddyman** [comment]
Yes. MMM-AssistantMk2 has been depreciated and will no longer be updated. 

MMM-GoogleAssistant is the new project that will replace it.

**Comment by josooik** [comment]
Thank you

**Comment by bugsounet** [comment]
I confirm, MMM-AssistantMk2 is close
MMM-GoogleAssistant replace it ;) 

@sudoreddyman : Thanks for your wiki contribution in A2D
