### ISSUE TITLE
Regist gaction

### ISSUE THREAD

**Issue by broadstar9** [bugsounet/MMM-GoogleAssistant#192]
Thank you very much for providing a great product.

My question is about action.
I just followed wiki. but i can not do [Auth action_package.json as first time.].
> cd ~/MagicMirror/modules/MMM-GoogleAssistant/utility
> ./gactions test --action_package ../tmp/action_package.json --project *YOUR_PROJECT_ID*

Please check capture image. and let me know how can i do.
Thank you.

![image](https://user-images.githubusercontent.com/74710654/99902172-1bd29400-2cff-11eb-977d-512929ff749b.png)

**Comment by bugsounet** [comment]
hi it's a google issue, you can't make action with a rpi. just with Mac or linux os

This feature will be removed in the last release
