### ISSUE TITLE
Google authentification problem

### ISSUE THREAD

**Issue by jjun0322** [bugsounet/MMM-GoogleAssistant#193]
Thank you very much for providing q great products.

I just followed wiki. But here is the result on my mirror

I try several setting in the oaut authorisation screen of google console.

I put the 'credentials.json' file on the MMM-GoogleAssistant folder and entered the 'node auth_and_test.js' command.

A new wondow opens and when i enter the email, i get an approval error like the picture below.

Is there a solution? 
Please answer.
Thanks in advance

![20201208_165659](https://user-images.githubusercontent.com/75663381/101455761-68140a00-3976-11eb-8e19-53a41b171567.jpg)

**Comment by bugsounet** [comment]
related to https://github.com/bugsounet/MMM-GoogleAssistant/issues/179
