### ISSUE TITLE
Broadcast feature does not work

### ISSUE THREAD

**Issue by jorickjuh** [bugsounet/MMM-GoogleAssistant#197]
Is it possible to make the broadcast feature work?

**Comment by bugsounet** [comment]
?

**Comment by jorickjuh** [comment]
Well, when I say, broadcast, dinner is ready. It won't broadcast to my mirror. But it does to other devices?

**Comment by bugsounet** [comment]
Not include on the assistant sdk project

Google Sdk project is +/- Google Assistant demo

**Comment by jorickjuh** [comment]
So where can I change that?

**Comment by bugsounet** [comment]
You can do it by buying a Google license and doing your own project (see Google developper commercial contact)
