### ISSUE TITLE
I didn't hear back from GA

### ISSUE THREAD

**Issue by vtdang1194** [bugsounet/MMM-GoogleAssistant#198]
Thank you very much for providing great products.
I just followed wiki. But here is the result on my mirror
![6cb8218f1ac5ea9bb3d4](https://user-images.githubusercontent.com/75298030/103202274-8beac000-4924-11eb-9557-c59cdb40d1c7.jpg)
"mmap() failed: Không thể cấp phát bộ nhớ"
 (mmap() failed:cannot allocate memory)
This prevents GA from making a sound when responding

https://user-images.githubusercontent.com/75298030/103202349-bccaf500-4924-11eb-9644-068436218539.mp4

Do you have an idea ? Thanks in advance

**Comment by bugsounet** [comment]
Hi,

yes I have an idea. Just read wiki ;)

**Comment by vtdang1194** [comment]
> Hi,
> 
> yes I have an idea. Just read wiki ;)

Yes! I have seen it! thank you :+1:

**Comment by phungorquan** [comment]
Hi @vtdang1194  , could you open youtube or web when using G.A.
It could not work for since a month ago
