### ISSUE TITLE
Problème Google Assistant

### ISSUE THREAD

**Issue by jeff44850** [bugsounet/MMM-GoogleAssistant#2]
Bonjour
Après l'installation et l'utilisation avec le mot clé  "jarvis" le module fonctionne correctement sur quelques essais ( nombre aléatoire ) et par la suite à la détection du mot clé Magic Mirror redémarre !
Avez-vous déjà entendu parler du problème ou une idée ?
cordialement

**Comment by bugsounet** [comment]
Bonjour Jeff,

Oui, je confirme. Jj'ai remarquer cela aussi, par moment il ne veux pas détecter de mot clé... et tout a coup, quelques minute/ seconde plus tard cela remarche.

J'arrive a atténuer le problème en activant le mode `debug` dans le fichier de configuration.
Je vais essayer de tracer/pister le problème afin de corriger

**Comment by bugsounet** [comment]
voila le problème est maintenant résolu.
Essayer de mettre a jours vers la version 1.1.0

Désolé pour le retard,
Cédric

**Comment by jeff44850** [comment]
Merci beaucoup
Je met à jour très vite
Bonne journée
Cordialement
