### ISSUE TITLE
How to add new Custom hotword?

### ISSUE THREAD

**Issue by timbuktu031** [bugsounet/MMM-GoogleAssistant#20]
How to add new Custom hotword?
I can't find model directory.

**Comment by bugsounet** [comment]
Actually not yet supported, maybe coded in future...
there is no model directory displaying because i use my personal npm library

If you really want this feature quickly,
You can Fork this program and make your own project with your recoding choice

**Comment by timbuktu031** [comment]
> Actually not yet supported, maybe coded in future...
> there is no model directory displaying because i use my personal npm library
> 
> If you really want this feature quickly,
> You can Fork this program and make your own project with your recoding choice

Ok! thank you
