### ISSUE TITLE
GA startup error and google home registration

### ISSUE THREAD

**Issue by tradingbros** [bugsounet/MMM-GoogleAssistant#200]
My google assistant works fine but sometimes at startup it does not respond for a while and later gives - mic configuration error on the GA search bar . Also i have successfully registered my device on google home but i cannot connect to it from my google home app on my phone ,

**Comment by bugsounet** [comment]
> My google assistant works fine but sometimes at startup it does not respond for a while and later gives - mic configuration error on the GA search bar

Maybe internet connexion lost

> Also i have successfully registered my device on google home but i cannot connect to it from my google home app on my phone 

I have deprecied this functionality (so many coding part for yourself and you can't control your mirror with it), see in google developer for helping, if you really want
