### ISSUE TITLE
Multiple Pages?

### ISSUE THREAD

**Issue by PineMaster** [bugsounet/MMM-GoogleAssistant#23]
Hello is it possible that we can have a command by which we can switch pages or hide all pages, so like page 1 is the google assistant and page 2 has all the other modules? and there is also a hide option by which we can hide it

Thanks for making this awesome project!

**Comment by bugsounet** [comment]
I don't know why you want to hide the assistant
because it's already hidden and it's shown only on activate

**Comment by PineMaster** [comment]
does it overlap the modules showing before its activated?

**Comment by bugsounet** [comment]
The version 2 of GA is coded when activating :
 * hide all module
 * take place in full screen to GA
When finish talking:
Hide GA
Shown all module

**Comment by PineMaster** [comment]
Oh thanks!
