### ISSUE TITLE
mmap() failed: Cannot allocate memory

### ISSUE THREAD

**Issue by PineMaster** [bugsounet/MMM-GoogleAssistant#24]
Hello, I get the error `mmap() failed: Cannot allocate memory` when I ask the assistant a question, it works (the assistant answers the question) but I get this error in the terminal

**Comment by bugsounet** [comment]
Read [this](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Installation#googleassistant-module-works-only-with-html5-audio)

**Comment by PineMaster** [comment]
fixed, thanks
