### ISSUE TITLE
Youtube is not working

### ISSUE THREAD

**Issue by Ryan792** [bugsounet/MMM-GoogleAssistant#27]
It only shows youtube links when I ask for youtube videos. I have also added mmm-youtube module. Is youtube not compatible ? or Did I miss some config? :(

**Comment by bugsounet** [comment]
MMM-GoogleAssistant not read directly Youtube or other links.
You need to install MMM-Assistant2Display to do this

**Comment by Ryan792** [comment]
Thank you so much. I also have MMM-Assistant2Display, still doesn't work. I just posted my config there.
