### ISSUE TITLE
Need help with microphone setup.

### ISSUE THREAD

**Issue by aamir6629** [bugsounet/MMM-GoogleAssistant#29]
I have raspberry pi3 running buster.
I want to setup PS3 eye as a microphone on it to be used for MMM-GoogleAssistant

No clear direction or setup procedure are available online. So need your help.
Thanks in advance

**Comment by bugsounet** [comment]
i have updated checkmic part.

use `npm run update` to update

and it will help you to determinate your micConfig {}

**Comment by lxne** [comment]
> so ... try:
> `device : "plughw:2",`
> in your `micConfig {}`

Did it work with these settings?

**Comment by bugsounet** [comment]
Hi, I think is now solved.
