### ISSUE TITLE
Update from 2.0

### ISSUE THREAD

**Issue by Ryan792** [bugsounet/MMM-GoogleAssistant#33]
I am using Magic mirror v2.11.0 & google assistant 2.0, so in order to update google assistant do I need to run both commands?

"npm run update"
&
"npm run rebuild"

or only "npm run rebuild"? I also need to know if I can simply use "npm run update" to update MMM-Assistant2Display.

**Comment by bugsounet** [comment]
only `npm run update` is needed

`npm run rebuild` is need ONLY if a new version of MagicMirror is installed

**Comment by Ryan792** [comment]
I used "npm run update", installation went ok, but i am getting black screen now..

**Comment by Ryan792** [comment]
Thanks
