### ISSUE TITLE
Change audio source

### ISSUE THREAD

**Issue by hm1234** [bugsounet/MMM-GoogleAssistant#37]
I am trying to use my google aiy hat speaker and mic. I got it working mic works and trigger but the speaker I only hear the chime but does not play any audio. I wanted to know if there is somewhere to  change the audio source?

**Comment by bugsounet** [comment]
you can audio change source is on the desktop (volume icon)
MMM-GoogleAssistant is default output with HTML5

after if you only hear the chime try this:

```sh
apt list --installed | grep pulseaudio
```

if installed ... This module is not compatible with this one
I have actually no solutions for use it

**Comment by hm1234** [comment]
Thank you I'll try it

**Comment by hm1234** [comment]
@bugsounet I got things working just a quick question while the assistant talking is there a way to trigger it while talking like stop it. I see that the mic turns off while the assistant is talking and turn back on when it's done?

**Comment by bugsounet** [comment]
unfortunately, this is not planned
