### ISSUE TITLE
Recipe 

### ISSUE THREAD

**Issue by hm1234** [bugsounet/MMM-GoogleAssistant#38]
I am trying to create a recipe where if I say page one, two, three then it will change to the respective page. I have created this but I get an error when loading mm. https://pastebin.com/t41XTCKQ

**Comment by bugsounet** [comment]
hi, notificationExec field is not correct
```
notificationExec: {
        notification: "noti_name",
        payload: "your_payload"
}
```

don' t understand why using command plugins "PAGES" in this case
I think you can delete it ... it will return error with each notification received (PAGES command not exist)

**Comment by bugsounet** [comment]
Hi, I think is now solved.
