### ISSUE TITLE
Audio open error

### ISSUE THREAD

**Issue by lzfilms4** [bugsounet/MMM-GoogleAssistant#39]
Hello,
After starting the mirror, an error is issued in the console:
warn: arecord:828:
warn: audio open error: no such file or directory

What I have to do?

**Comment by bugsounet** [comment]
since last RPI firmware audio input/ouput have change

try with `npm run update` , the check micConfig setup can help to determinate your new micConfig device value

**Comment by bugsounet** [comment]
Hi, I think is now solved.
