### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by lillaeriika** [bugsounet/MMM-GoogleAssistant#44]
Hey!

I'm not sure if I understand the position options in the config. Can you have anything else than fullscreen-above as position? Is there any way to have it like the old MK2, the response not being on top of all the other modules?

/Erik

**Comment by lxne** [comment]
Good question. I tried a view things but nothing ever changed anything.

**Comment by bugsounet** [comment]
Hi, now all position don't change ui, GA ui is in iframe.
It don't take any place in the mirror screen. It only showing when calling assistant.
I don't modify it sorry.
If you want an old ui interface, you can use AMk2 v3.5

**Comment by Joshsamuel101** [comment]
Is there a way to modify the iFrame size so that the links are not full screen?

Had in mind something similar to this: https://github.com/l0b5ter/KeyDisplayed

**Comment by bugsounet** [comment]
GA don't show any links, it's MMM-Assistant2Display job and it's displayed on Full screen size ([like this](https://raw.githubusercontent.com/bugsounet/MMM-Assistant2Display/dev/screenshot/screenshot2.png) with auto scrolling)
I don't know what can i do more

**Comment by destiny1976** [comment]
is it possible to shrink the screensize of GA to 1x1 pixel at idle/listening mode? Is it possible only results are fullscreen?
I use a touchscreen, but when GA is idle, i can't use touchscreen anymore, because GA is always fullscreen on top.

**Comment by bugsounet** [comment]
no, sorry... I don't code this ...
The module is an iframe for displying and have NO position in the screen to do that.

If you want this Feature, read and install AMk2 v3.5 repo (but not compatible with A2D)
