### ISSUE TITLE
MMM-Selfieshot 

### ISSUE THREAD

**Issue by clify007** [bugsounet/MMM-GoogleAssistant#46]
Hi,
Please help me in setting up command to activate MMM-Selfieshot. I'm not good with programming parts and just keep following the steps.
Magic mirror is working fine, google assistant is working great. 
I want to add more functionality in terms of commands that can be used, 

Appreciate it if you could guide me in the right direction.

Thanks in advance

**Comment by bugsounet** [comment]
hi, i don't use this module
but I think you can try to do an recipe to ask to take an selfie
You have some sample of recipe in recipes directory and spotify recipe can help you to do it
