### ISSUE TITLE
I cant install.

### ISSUE THREAD

**Issue by uok825** [bugsounet/MMM-GoogleAssistant#48]
I type npm install but when i got this error.
[https://prnt.sc/t1izqt](https://prnt.sc/t1izqt)

**Comment by bugsounet** [comment]
hi,
Just Read [requirements](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Installation#requirements)
You have raspbian 9

**Comment by uok825** [comment]
> hi,
> Just Read [requirements](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Installation#requirements)
> You have raspbian 9
thats hurt :(

**Comment by bugsounet** [comment]
Sorry, if you want to use it, you can try to `apt-get dist-upgrade`
It will upgrade your OS to lasted version

**Comment by uok825** [comment]
> Sorry, if you want to use it, you can try to `apt-get dist-upgrade`
> It will upgrade your OS to lasted version

[https://prnt.sc/t1k59k](https://prnt.sc/t1k59k)

**Comment by bugsounet** [comment]
hi,
main problem is now solved.
Reopen it if needed
