### ISSUE TITLE
web browser or web result doesn't show up

### ISSUE THREAD

**Issue by Smeili06** [bugsounet/MMM-GoogleAssistant#502]
When I ask my assistant sth it can't immediately answer, it says: "Here's a result from the web". The problem is: nothing happens. I just get a blank screen and have no idea what I did wrong. Maybe it's sth in the configuration, but I tried many things and still didn't fix the problem.

**Comment by bugsounet** [comment]
This functionality need [EXT-Browser](https://wiki.bugsounet.fr/en/EXT-Browser)

**Comment by bugsounet** [comment]
Hi, thanks to open a ticket in www.bugsounet.fr
