### ISSUE TITLE
Trying to use MMM-Google Assistant to add events to Google Tasks, Google Calendar, etc.

### ISSUE THREAD

**Issue by emilegasbarri** [bugsounet/MMM-GoogleAssistant#503]
Hey, 

I wanted to use MMM-Google Assistant to add events to Google Tasks and Google Calendar, though whenever I ask it to, it responds "First I'll need your permission to give Personal Results. You can make that change in Google Assistant Settings on your phone."

![20240725_190639](https://github.com/user-attachments/assets/a7601785-879e-42b0-a34e-d0471efda179)

Though, I cannot find a way to enable this through Google Assistant settings on my phone as MagicMirror is not registered as an "Assistant Device".

Also, recently the Google API was changed, so it now only has limited capabilities with IFTTT and other automation platforms, making them useless for what I wish to do.

Any help with activating "Personal Results" for MMM-Google Assistant would be appreciated, thanks!

**Comment by bugsounet** [comment]
Hi, thanks to open a ticket in www.bugsounet.fr
