### ISSUE TITLE
[GA] [DATA] [ERROR] [FATAL] Assistant: tokenGA.json file not found ! 

### ISSUE THREAD

**Issue by MMAik100** [bugsounet/MMM-GoogleAssistant#507]
I had to rebuild my Rasberry PI4 and I am a beginner.   This is the latest error message.  Can someone advise me what to do?

**Comment by lxne** [comment]
There obviously is no tokenGA.json in your GA-module folder. Do you have credentials?
https://wiki.bugsounet.fr/MMM-GoogleAssistant/SetupCredentials

**Comment by MMAik100** [comment]
I did, but when I rebuilt the computer, I wiped everything instead of backing some stuff up.  I have the secret code and my google project is still there but I don't know how to generate or download the tokenGA again.

**Comment by MMAik100** [comment]
i was able to figure it out.  thank you

**Comment by bugsounet** [comment]
Hi, I think you forgot [this](https://wiki.bugsounet.fr/MMM-GoogleAssistant/Beforethefirststart#before-the-first-launch-of-mmm-googleassistant).

**Comment by MMAik100** [comment]
exactly.   I need to read more.  Thank you
