### ISSUE TITLE
Magic mirror shuts down with error: You can't use MMM-GoogleAssistant in server mode

### ISSUE THREAD

**Issue by RpiUnoo** [bugsounet/MMM-GoogleAssistant#513]
I installed the module following all the steps listed on your page. I'm using Rapberry Pi 4 but when I launch the mirror it shuts down with the error: "You can't use MMM-GoogleAssistant in server mode". I'm not launching my mirror in server mode but still it displays this error!
![WhatsApp Image 2024-08-21 at 12 34 48_0104b1d3](https://github.com/user-attachments/assets/518b30a9-d0b1-444b-b81f-9297efcd21eb)

**Comment by bugsounet** [comment]
Hi, thanks to open a ticket in www.bugsounet.fr
