### ISSUE TITLE
i don't understand config file..

### ISSUE THREAD

**Issue by wjdalsrbekt** [bugsounet/MMM-GoogleAssistant#56]
Hello, I am a student who wants to handle magic mirror. I wrote the config file after looking at the sample, but nothing appears in my magic mirror and it doesn't work. How do I write this? I'd appreciate it if you could let me know.

**Comment by lxne** [comment]
Have you installed the module without errors?
Did you test the mic and sound output?
What did you write in your config.js?

**Comment by bugsounet** [comment]
Hi, we think, your issue is now solved
reopen it if necessary
