### ISSUE TITLE
MMM-GoogleAssistant create own hotword

### ISSUE THREAD

**Issue by TheLoopFlesh** [bugsounet/MMM-GoogleAssistant#63]
Hi guys, I want to know how to add my Hotword from maybe snowboy.kitt.ai/dashoboard or others beacause default hotword like "Alexa" "Jarvis" dont react allways. I create the hotword and I want to config it. I want to configurate hotword the same like google assistant on phone, It react only for my voice. U know how to do that?

**Comment by bugsounet** [comment]
sorry, it's not yet implented and it's not planned actually

**Comment by TheLoopFlesh** [comment]
Okey, so how to fix that default hotword like "Alexa" "Jarvis" dont react allways.

**Comment by bugsounet** [comment]
verify your Mic level (in RPI desktop -> icon volume -> output device mixer)
and/or ajust `Sensitivity` level feature of snowboy. read [this part](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Configuration-Structure#field-snowboy-)

my personnal setting: 
 * mic level : 40%
 * Sensitivity of snowboy : 0.6

Attention : 
 * it's depend of your microphone type
 * everyone have not the same microphone
 * so ... settings are not the same for everyone
 * If you boost too much your mic level : you can have some fake positive keyword
 * in reverse, if mic level is too low ... it wil not reconize any keyword
 * if you boost too much your sensitivity of snowboy: you can have some fake positive keyword too
 * in reverse, if sensitivity is too low... it will not reconize your prefered keyword
 * ---> search the best value

For your information:
my keyword is `jarvis` and no issue for me.
Snowboy reconize my keyword at 5 meters without problem :)
Not many fake positive when there is many people in the room

So : 
 * in first, let's check your mic level
 * adjust sensitivity after

**Comment by bugsounet** [comment]
Hi
Reopen this issue if needed
