### ISSUE TITLE
hi.. my assitant is not working, I attach my file status in detail. pls help me

### ISSUE THREAD

**Issue by NightRiders22** [bugsounet/MMM-GoogleAssistant#68]
I installed it by referring to the wiki. There was no error message.

i read Google Assistant Setup, I proceeded in order and passed the part to test at the prompt

But it doesn't work to see if I missed Attach my file

do npm start

and magic mirror is working but google assitant is not working

plz help me...

my mic and speaker is good working

test in onlinemictest and youtube

I will wait for your reply every hour Thank you

![구글어시스턴트 모듈구성 캡처](https://user-images.githubusercontent.com/50954095/86005531-be882e80-ba4f-11ea-8c30-d3cc1996bbba.JPG)
[configjs.txt](https://github.com/bugsounet/MMM-GoogleAssistant/files/4845457/configjs.txt)
[MMM-GoogleAssistantjs.txt](https://github.com/bugsounet/MMM-GoogleAssistant/files/4845458/MMM-GoogleAssistantjs.txt)

**Comment by NightRiders22** [comment]
my mic and speaker is good working

test in onlinemictest and youtube

**Comment by bugsounet** [comment]
hi, in your config, you use
```		{
			  module: "MMM-AssistantMk2",
			  position: "top_right",
			  config: {
				useWelcomeMessage: "brief today",
			    coordinates: {
			      latitude: 51.5033640,
			      longitude: -0.1276250,
			    },
			    record: { // put there configuration generated by auto-installer
			      recorder : "arecord",
			      device: "plughw:1"
			    },
			  }
		},
```
and you don't use MMM-GoogleAssistant
I don't know what do you want to do with the modified file of MMM-GoogleAssistant
and what do you want to search to do but it's not possible with this method

May be the simple solution for you is using MMM-AssistantMk2

**Comment by NightRiders22** [comment]
Thank you for your answer. I've solved it. While looking for a way, I think it was corrupted while referring to other settings.

I tried to give up after fixing this for 4 days

If you change Model: "jarvis", randomly, will it work?

**Comment by bugsounet** [comment]
Sorry, i don't support helping of MMM-AssistantMk2 module
[Please read the wiki part of this module](https://github.com/bugsounet/MMM-AssistantMk2/wiki)
