### ISSUE TITLE
ALSA Problem

### ISSUE THREAD

**Issue by baudi94** [bugsounet/MMM-GoogleAssistant#72]
Hey there, I'm getting the following problem when I start my MM.

"[SNOWBOY] Retry restarting...
[2020-07-02 19:34:51.108] [LOG]    [LPCM16] WARN: ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
arecord: main:828:"

and it keeps retrying and restarting.

I'm kinda a noob, what do I do wrong?

**Comment by bugsounet** [comment]
> Invalid value for card

means your micConfig is not configured correctly

**Comment by baudi94** [comment]
> > Invalid value for card
> 
> means your micConfig is not configured correctly

Can you help me fix this? tried to edit the asound.conf but nothing seems to work

**Comment by bugsounet** [comment]
what micConfig check says when you have installed it?
