### ISSUE TITLE
Mic GA

### ISSUE THREAD

**Issue by nguyenanhminh97** [bugsounet/MMM-GoogleAssistant#83]
My everything is fine, but GA can only hear me when the mic is near, I want to increase the recording ability of the mic farther

**Comment by lxne** [comment]
Play with settings 'audioGain' and 'Sensitivity':
https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Configuration-Structure#field-snowboy-
Or use better mic.

**Comment by bugsounet** [comment]
Hi,
 in first check your Mic level in your RPI desktop
Volume icon -> Output device and select your Mic device
Generaly 40-50% is a good choice
