### ISSUE TITLE
Button GA

### ISSUE THREAD

**Issue by nguyenanhminh97** [bugsounet/MMM-GoogleAssistant#89]
I want to activate GA with a button instead of a command.
So, how can i access module Google Assistant when i press a button ( do not use keyboard and mouse )

**Comment by bugsounet** [comment]
Sorry, this feature can't be coded with the actual GA core program

It's only on voice activating for displaying GA UI
what's why there no UI displayed on standby mode
GA Take no place on screen for take place to another module
