### ISSUE TITLE
can i get help on MMM-AssistantMk2 ??

### ISSUE THREAD

**Issue by MWHM212** [bugsounet/MMM-GoogleAssistant#99]
can i get help on MMM-AssistantMk2 ??

**Comment by bugsounet** [comment]
Hi, there it is MMM-GoogleAssistant issue place and not MMM-AssistantMk2.
Please open an issue on MMM-AssistantMK2 repository

**Comment by MWHM212** [comment]
you said 
I have open Issue but I will give no helping for this module.
